### ISSUE TITLE
Allocate more resources with PBS backend

### ISSUE THREAD

**Issue by hchintalapudi** [ENCODE-DCC/atac-seq-pipeline#294]
Hi,
Firstly, thank you for the this amazing pipeline.
I was trying to run it with PBS backend. I installed everything and it runs fine.
But I see that bowtie2 is running on single thread (100%cpu with top -u username) on my compute node.
I also saw in https://github.com/ENCODE-DCC/caper/issues/27 that it is not advised to allocate resources with "--pbs-extra-param" as the pipeline will take care of it.
But bowtie2-align-s has been running for more than one day now.
How can I allocate more threads/resources with pbs backend?
My caper version is 0.6.4

[my_template_2.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/5482196/my_template_2.json.txt)
[default.conf.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/5482204/default.conf.txt)

**Comment by leepc12** [comment]
You are using outdated Caper. Please get the latest one (>=v1.4.1) and try again. I remember that I fixed some PBS resource parameter issues around v1.3.

BTW bowtie2 takes long.

Also, latest ATAC-seq pipeline has adaptive resource allocation. You only need to specify number of threads for each task (e.g. `atac.align_cpu` and `atac.call_peak_cpu`). I recommend to use defaults, which means not touching any resource parameters.

**Comment by hchintalapudi** [comment]
Thanks for the suggestion.
I upgraded caper to 1.4.1 with pip install caper --upgrade and downloaded the new version of the pipeline (1.9.1)
So, our pipeline infrastructure supports 'mksub' instead of qsub and last time with the new versions I changed the qsub command in the file 'caper_backend.py' to mksub (in the pbs subroutine) and it worked fine.
I did the same this time, changed the qsub to mksub in ~/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cromwell_backend.py and it reflects in script.submit when I run the pipeline.
However the pipline doesn't run! Am I missing something with the new versions? 

Thanks.
[cromwell.out.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/5487885/cromwell.out.txt)
[atac_10-7-20_template_full.json.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/5487886/atac_10-7-20_template_full.json.txt)

**Comment by leepc12** [comment]
Can you make an alias of it instead of directly modifying the code? You can add the following to your `~/.bashrc`
```
alias qsub=mksub
```

**Comment by hchintalapudi** [comment]
I tried adding it and 'source'ed the ~/.bashrc.
The pipeline still crashes. 
script.submit in call-read_genome_tsv shows qsub again:

#!/bin/bash
if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=; fi;

echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/script" | \
qsub \
    -N cromwell_d069c847_read_genome_tsv \
    -o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/stdout \
    -e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/stderr \
    -lnodes=1:ppn=1:mem=2048mb \
    -lwalltime=1:0:0 \
     \
     \
     \
    -V

stderr.background:
qsub: submit error (Command syntax invalid MSG=Invalid Syntax)

**Comment by leepc12** [comment]
```
echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/script" |
qsub
-N cromwell_d069c847_read_genome_tsv
-o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/stdout
-e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/d069c847-6b30-4a14-a038-8f4745627e47/call-read_genome_tsv/execution/stderr
-lnodes=1:ppn=1:mem=2048mb
-lwalltime=1:0:0



-V
```

This is the actual command line to be submitted to the PBS engine. Does `mksub` support those parameters? e.g. -o,  -e,  -lnodes=, -lwalltime, -V.

**Comment by hchintalapudi** [comment]
Hi,
Yes, all those parameters work like normal.

This is from the caper 0.6.4 (and pipeline version 1.7.0) script.submit :
#!/bin/bash
echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/78426a0d-b91d-48b6-938d-33328f030b14/call-read_genome_tsv/execution/script #         if [ -z \"$SINGULARITY_BINDPATH\" ]; then         export SINGULARITY_BINDPATH=; fi;         if [ -z \"$SINGULARITY_CACHEDIR\" ]; then         export SINGULARITY_CACHEDIR=; fi;         singularity exec --cleanenv --home /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/78426a0d-b91d-48b6-938d-33328f030b14/call-read_genome_tsv                   /bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/78426a0d-b91d-48b6-938d-33328f030b14/call-read_genome_tsv/execution/script" | mksub         -N cromwell_78426a0d_read_genome_tsv         -o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/78426a0d-b91d-48b6-938d-33328f030b14/call-read_genome_tsv/execution/stdout         -e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/78426a0d-b91d-48b6-938d-33328f030b14/call-read_genome_tsv/execution/stderr         -lselect=1:ncpus=1:mem=4000mb         -lwalltime=1:0:0                                    -V

And it worked fine. I cannot understand what's new that's making the pipeline crash.
Does the genome.tsv have to be rebuilt with the newer pipeline's scripts/build_genome_data.sh?

Thanks.

**Comment by leepc12** [comment]
I changed PBS resource parameter around v1.3.

Old version's submission parameters.
```
-lselect=1:ncpus=1:mem=4000mb
```

New version's submission parameters.
```
-lnodes=1:ppn=1:mem=2048mb
```

**Comment by hchintalapudi** [comment]
Thank you. I changed the line to reflect the old style parameters in cromwell_backend.py:

class CromwellBackendPBS(CromwellBackendLocal):
    TEMPLATE_BACKEND = {
        'config': {
            'default-runtime-attributes': {'time': 24},
            'script-epilogue': 'sleep 30 && sync',
            'runtime-attributes': dedent(
                """\
                String? docker
                String? docker_user
                Int cpu = 1
                Int? gpu
                Int? time
                Int? memory_mb
                String? pbs_queue
                String? pbs_extra_param
                String? singularity
                String? singularity_bindpath
                String? singularity_cachedir
            """
            ),
            'submit': dedent(
                """\
                if [ -z \\"$SINGULARITY_BINDPATH\\" ]; then export SINGULARITY_BINDPATH=${singularity_bindpath}; fi; \\
                if [ -z \\"$SINGULARITY_CACHEDIR\\" ]; then export SINGULARITY_CACHEDIR=${singularity_cachedir}; fi;

                echo "${if !defined(singularity) then '/bin/bash ' + script
                        else
                          'singularity exec --cleanenv ' +
                          '--home ' + cwd + ' ' +
                          (if defined(gpu) then '--nv ' else '') +
                          singularity + ' /bin/bash ' + script}" | \\
                qsub \\
                    -N ${job_name} \\
                    -o ${out} \\
                    -e ${err} \\
                    **${true="-lselect=1:ncpus=" false="" defined(cpu)}${cpu}${true=":mem=" false="" defined(memory_mb)}${memory_mb}${true="mb" false="" defined(memory_mb)} \\**
                    ${'-lwalltime=' + time + ':0:0'} \\
                    ${'-lngpus=' + gpu} \\
                    ${'-q ' + pbs_queue} \\
                    ${pbs_extra_param} \\
                    -V
            """
            ),
            'exit-code-timeout-seconds': 180,
            'kill': 'qdel ${job_id}',
            'check-alive': 'qstat ${job_id}',
            'job-id-regex': '(\\d+)',
        }
    }

And it runs to generate the first job and I see the job number (unlike the last time) in stdout.background:
15232
2024478.pearl.hpcc.dartmouth.edu

But it gets killed with 'Exit_status=-9' and the pipeline stays idle and does nothing.
script.submit:
#!/bin/bash
if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=; fi;

echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/script" | \
qsub \
    -N cromwell_0caadb4f_read_genome_tsv \
    -o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stdout \
    -e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stderr \
    -lselect=1:ncpus=1:mem=2048mb \
    -lwalltime=1:0:0 \
     \
     \
     \
    -V

So this is the error message from the pbs server I got:
PBS Job Id: 2024478.pearl.hpcc.dartmouth.edu
Job Name:   cromwell_0caadb4f_read_genome_tsv
Exec host:  n06/35
Aborted by PBS Server 
Job cannot be executed
See Administrator for help
Exit_status=-9
resources_used.cput=00:00:00
resources_used.vmem=0kb
resources_used.walltime=00:00:01
resources_used.mem=0kb
resources_used.energy_used=0
req_information.task_count.0=1
req_information.lprocs.0=1
req_information.total_memory.0=2097152kb
req_information.memory.0=2097152kb
req_information.thread_usage_policy.0=allowthreads
req_information.hostlist.0=n06:ppn=1
req_information.task_usage.0.task.0={"task":{"cpu_list":"34","mem_list":"0","cores":0,"threads":1,"host":"n06"}}
Error_Path: discovery7.hpcc.dartmouth.edu:/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stderr
Output_Path: discovery7.hpcc.dartmouth.edu:/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stdout

~/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/ has many caper and cromwell files.
Apart from cromwell_backend.py, are there any other files which need editing to reflect the changes like above?
Thank you.

**Comment by hchintalapudi** [comment]
Hi, just an update:
The pipeline seems to be running now, but I'm back to the same problem.

Here is the screenshot of top command on my compute node:
<img width="606" alt="Screen Shot 2020-11-06 at 8 16 17 AM" src="https://user-images.githubusercontent.com/26474881/98372639-15100580-200c-11eb-8508-613d8a4bc40d.png">

atac.align (bowtie2) still runs on single thread even when atac-seq-pipeline/atac/5f84bfee-f3f1-4903-ab9d-32ca8c6a4e61/call-align/shard-0/execution/script.submit shows:
#!/bin/bash
if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=; fi;

echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/5f84bfee-f3f1-4903-ab9d-32ca8c6a4e61/call-align/shard-0/execution/script" | \
mksub \
    -N cromwell_5f84bfee_align \
    -o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/5f84bfee-f3f1-4903-ab9d-32ca8c6a4e61/call-align/shard-0/execution/stdout \
    -e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/5f84bfee-f3f1-4903-ab9d-32ca8c6a4e61/call-align/shard-0/execution/stderr \
    -lselect=1:ncpus=6:mem=5973mb \
    -lwalltime=48:0:0 \
     \
     \
     \
    -V

**Comment by hchintalapudi** [comment]
Hi,
I eventually am able to allocate resources with "--pbs-extra-param" but the pipeline crashes at call-filter stage.

/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/execution/stderr:
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 417, in <module>
    main()
  File "/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 350, in main
    filt_bam, args.out_dir, args.picard_java_heap)
  File "/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_task_filter.py", line 198, in mark_dup_picard
    dup_qc=dup_qc,
  File "/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 331, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=153790, PGID=153790, RC=1, DURATION_SEC=0.2
STDERR=Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/tmp.e12ca190
Exception in thread "main" java.lang.UnsupportedClassVersionError: picard/cmdline/PicardCommandLine : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
STDOUT=
ln: failed to access '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/execution/*.samstats.qc': No such file or directory
ln: failed to access '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/execution/*.dup.qc': No such file or directory
ln: failed to access '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/execution/*.bai': No such file or directory
ln: failed to access '/dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-1/attempt-2/execution/*.lib_complexity.qc': No such file or directory

I checked my java -version after activating conda:
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (Zulu 8.19.0.1-linux64) (build 1.8.0_112-b16)
OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-linux64) (build 25.112-b16, mixed mode)

Is Picard picking up my older version of java 1.7 outside of the conda env?
Some tips would be appreciated.
Thanks.

**Comment by leepc12** [comment]
Check your Java version It should be >=1.8.
Also, how did you define `--pbs-extra-param`?

Do command lines have trailing `\` for every line?

It looks like you have `\n` instead of `\\`?
```
qsub
-N cromwell_0caadb4f_read_genome_tsv
-o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stdout
-e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/0caadb4f-4a81-4bb7-85ad-4e1a6cf8c236/call-read_genome_tsv/execution/stderr
-lselect=1:ncpus=1:mem=2048mb
-lwalltime=1:0:0



-V
```

**Comment by hchintalapudi** [comment]
conda activate encode-atac-seq-pipeline
(encode-atac-seq-pipeline) [f0042dk@discovery7 RNAseq]$ java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (Zulu 8.19.0.1-linux64) (build 1.8.0_112-b16)
OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-linux64) (build 25.112-b16, mixed mode)

This is how I defined --pbs-extra-param:
caper run atac.wdl -i atac_10-7-20_template_full_tmp.json --pbs-extra-param " -lnodes=1:ppn=32" 2>enc.err

I see trailing '\' for every line. 
atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-0/execution/script.submit:
#!/bin/bash
if [ -z \"$SINGULARITY_BINDPATH\" ]; then export SINGULARITY_BINDPATH=; fi; \
if [ -z \"$SINGULARITY_CACHEDIR\" ]; then export SINGULARITY_CACHEDIR=; fi;

echo "/bin/bash /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-0/execution/script" | \
mksub \
    -N cromwell_06e46c13_filter \
    -o /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-0/execution/stdout \
    -e /dartfs-hpc/rc/lab/L/LeachLab/HIMANSHU/atac-seq-pipeline/atac/06e46c13-4984-422c-9e74-65959c5635d1/call-filter/shard-0/execution/stderr \
    -lselect=1:ncpus=4:mem=11309mb \
    -lwalltime=24:0:0 \
     \
     \
     -lnodes=1:ppn=32 \
    -V

**Comment by leepc12** [comment]
Sorry for late response.
This should be fixed in the latest caper.
